function setPointerShape(idNumber)
B = 1;t = nan;o = 2;
switch idNumber
    case 1
        pointerShapeData = [ ...
            t t t t B B B B t t t t t t t t ; ...
            t t B B o o o o B B t t t t t t ; ...
            t B o o o o o o o o B t t t t t ; ...
            t B o o o B B o o o B t t t t t ; ...
            B o o o o B B o o o o B t t t t ; ...
            B o o B B B B B B o o B t t t t ; ...
            B o o B B B B B B o o B t t t t ; ...
            B o o o o B B o o o o B t t t t ; ...
            t B o o o B B o o o B t t t t t ; ...
            t B o o o o o o o o B t t t t t ; ...
            t t B B o o o o B B B B t t t t ; ...
            t t t t B B B B t t B B B t t t ; ...
            t t t t t t t t t t t B B B t t ; ...
            t t t t t t t t t t t t B B B t ; ...
            t t t t t t t t t t t t t B B B ; ...
            t t t t t t t t t t t t t t B B ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[7 7]);
    case 2
        pointerShapeData = [ ...
            t t t t B B B B t t t t t t t t ; ...
            t t B B o o o o B B t t t t t t ; ...
            t B o o o o o o o o B t t t t t ; ...
            t B o o o o o o o o B t t t t t ; ...
            B o o o o o o o o o o B t t t t ; ...
            B o o B B B B B B o o B t t t t ; ...
            B o o B B B B B B o o B t t t t ; ...
            B o o o o o o o o o o B t t t t ; ...
            t B o o o o o o o o B t t t t t ; ...
            t B o o o o o o o o B t t t t t ; ...
            t t B B o o o o B B B B t t t t ; ...
            t t t t B B B B t t B B B t t t ; ...
            t t t t t t t t t t t B B B t t ; ...
            t t t t t t t t t t t t B B B t ; ...
            t t t t t t t t t t t t t B B B ; ...
            t t t t t t t t t t t t t t B B ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[7 7]);
    case 3
        pointerShapeData = [ ...
            t t t t t t t B B t t t t t t t ; ...
            t t t B B o B o o B B B t t t t ; ...
            t t B o o B B o o B o o B t t t ; ...
            t t B o o B B o o B o o B t B t ; ...
            t t t B o o B o o B o o B B o B ; ...
            t t t B o o B o o B o o B o o B ; ...
            t B B o B o o o o o o o o o o B ; ...
            B o o B B o o o o o o o o o o B ; ...
            B o o o B o o o o o o o o o B t ; ...
            t B o o o o o o o o o o o o B t ; ...
            t t B o o o o o o o o o o o B t ; ...
            t t B o o o o o o o o o o B t t ; ...
            t t t B o o o o o o o o o B t t ; ...
            t t t t B o o o o o o o B t t t ; ...
            t t t t t B o o o o o o B t t t ; ...
            t t t t t B o o o o o o B t t t ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[8 8]);
    case 4
        pointerShapeData = [ ...
            t t t t t B B t t t t t t t t t ; ...
            t t t t B o o B t t t t t t t t ; ...
            t t t t B o o B t t t t t t t t ; ...
            t t t t B o o B t t t t t t t t ; ...
            t t t t B o o B B B B B t t t t ; ...
            t t t t B o o B o o B o B B t t ; ...
            t B B o B o o B o o B o B o B t ; ...
            B o o B B o o o o o o o o o B t ; ...
            B o o o B o o o o o o o o o B t ; ...
            t B o o o o o B o B o B o o B t ; ...
            t t B o o o o B o B o B o o B t ; ...
            t t B o o o o B o B o B o B t t ; ...
            t t t B o o o B o B o B o B t t ; ...
            t t t t B o o o o o o o B t t t ; ...
            t t t t t B o o o o B o B t t t ; ...
            t t t t t B B B B B t B B t t t ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[1 6]);
    case 5
        pointerShapeData = [ ...
            t t t t t t t o t t t t t t t t ; ...
            t t t t t t o B o t t t t t t t ; ...
            t t t t t o B B B o t t t t t t ; ...
            t t t t o B B B B B o t t t t t ; ...
            t t t t o o o B o o o t t t t t ; ...
            t t t o o t o B o t o o t t t t ; ...
            t t o B o t o B o t o B o t t t ; ...
            t o B B o o o B o o o B B o t t ; ...
            o B B B B B B B B B B B B B o t ; ...
            t o B B o o o B o o o B B o t t ; ...
            t t o B o t o B o t o B o t t t ; ...
            t t t o o t o B o t o o t t t t ; ...
            t t t t o B B B B B o t t t t t ; ...
            t t t t t o B B B o t t t t t t ; ...
            t t t t t t o B o t t t t t t t ; ...
            t t t t t t t o t t t t t t t t ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[8 8]);
    case 6
        pointerShapeData = [ ...
            t t t t t t t t t t B B t t t t ; ...
            t t t t t t t t t B B B B B t t ; ...
            t t t t t t t t B o B B B B B t ; ...
            t t t t t t t B o o B o B B B t ; ...
            t t t t t t B o o B o o o B B B ; ...
            t t t t t B o o B o o o B B B B ; ...
            t t t t B o o B o o o B o o B t ; ...
            t t t B o o B o o o B o o B t t ; ...
            t t t B o B o o o B o o B t t t ; ...
            t t t B B o o o B o o B t t t t ; ...
            t t B o o B o B o o B t t t t t ; ...
            t t B o o o B o o B t t t t t t ; ...
            t B o o o o B B B t t t t t t t ; ...
            t B B o B B t t t t t t t t t t ; ...
            t B B B t t t t t t t t t t t t ; ...
            B t t t t t t t t t t t t t t t ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[16 1]);
    case 8
        pointerShapeData = [ ...
            t t t t B B B B B B B B B B B B ; ...
            t t t t B o o o o o o o o o o B ; ...
            t t t t B o o o o B B o o o o B ; ...
            t t t t B o o o o B B o o o o B ; ...
            t t t t B o o o o B B o o o o B ; ...
            t t t t B o B B B B B B B B o B ; ...
            t t t t B o B B B B B B B B o B ; ...
            t t t t B o o o o B B o o o o B ; ...
            t t t t B o o o o B B o o o o B ; ...
            t t t t B o o o o B B o o o o B ; ...
            o o o t B o o o o o o o o o o B ; ...
            o B o o B B B B B B B B B B B B ; ...
            o B o B B o t t t t t t t t t t ; ...
            o B B B o t t t t t t t t t t t ; ...
            o B B o t t t t t t t t t t t t ; ...
            o o o t t t t t t t t t t t t t ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[16 1]);
    case 7
        pointerShapeData = [ ...
            t t t t t o B B B B B B B B B o ; ...
            t t t t o B o o o o o o o B B o ; ...
            t t t o B o o o o o o o B o B o ; ...
            t t o B o o o o o o o B o o B o ; ...
            t o B B B B B B B B B o o o B o ; ...
            t o B o o o o o o o B o o B o t ; ...
            t o B o o o o o o o B o B o t t ; ...
            t o B o o o o o o o B B o t t t ; ...
            t o B B B B B B B B B o t t t t ; ...
            t o o o o o B B o o o t t t t t ; ...
            o o o t o B B o t t t t t t t t ; ...
            o B o o B B o t t t t t t t t t ; ...
            o B o B B o t t t t t t t t t t ; ...
            o B B B o t t t t t t t t t t t ; ...
            o B B o t t t t t t t t t t t t ; ...
            o o o t t t t t t t t t t t t t ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[16 1]);
    case 9
        pointerShapeData = [ ...
            t t t t B B B B t t t t t t t t ; ...
            t t B B o o o o B B t t t t t t ; ...
            t B o o t t t t o o B t t t t t ; ...
            t B o t t t t t t o B t t t t t ; ...
            B o o t t t t t t t o B t t t t ; ...
            B o t t t t t t t t o B t t t t ; ...
            B o t t t t t t t t o B t t t t ; ...
            B o o t t t t t t o o B t t t t ; ...
            t B o t t t t t t o B t t t t t ; ...
            t B o o t t t t o o B t t t t t ; ...
            t t B B o o o o B B B B t t t t ; ...
            t t t t B B B B t t B B B t t t ; ...
            t t t t t t t t t t t B B B t t ; ...
            t t t t t t t t t t t t B B B t ; ...
            t t t t t t t t t t t t t B B B ; ...
            t t t t t t t t t t t t t t B B ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[7 7]);
    case 10
        pointerShapeData = [ ...
            t t t t t t t t t t t t t t t t ; ...
            t t t t t t t t t t t t t t t t ; ...
            t t t t t t t t t t t t t t t t ; ...
            t t t t B B t B B t B B t t t t ; ...
            t t t B o o B o o B o o B B B t ; ...
            t t t B o o B o o B o o B o o B ; ...
            t B B o B o o o o o o o o o o B ; ...
            B o o B B o o o o o o o o o o B ; ...
            B o o o B o o o o o o o o o B t ; ...
            t B o o o o o o o o o o o o B t ; ...
            t t B o o o o o o o o o o o B t ; ...
            t t B o o o o o o o o o o B t t ; ...
            t t t B o o o o o o o o o B t t ; ...
            t t t t B o o o o o o o B t t t ; ...
            t t t t t B o o o o o o B t t t ; ...
            t t t t t B o o o o o o B t t t ];
        set(gcf,'Pointer','custom','PointerShapeCData', ...
            pointerShapeData,'PointerShapeHotSpot',[8 8]);
    otherwise
        set(gcf,'Pointer','arrow')
end;