% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
% Created Mon Apr 11 17:21:26 IST 2016
%
% This script assumes these variables are defined:
%
%   buildingInputs - input data.
%   buildingTargets - target data.
clc
clear all;
close all;

% creating input and output feature matrix
INDIR = '/home/user/Documents/Ashish/inpFeats/';
OUTDIR = '/home/user/Documents/Ashish/outFeats/';
inFiles = dir(INDIR);
outFiles = dir(OUTDIR);
numUttsToWork = 300 ;
inputs = [];
targets = [];

count = 0 ;
for i = 1:size(inFiles,1)
        if(strcmp( regexp(inFiles(i).name,'feat','match'),'feat'))
            count = count + 1 ;
            disp(['Reading file ',num2str(count)]);
            infileName = inFiles(i).name; 
            outfileName = outFiles(i).name; 
            a = importdata(strcat(INDIR,infileName)); 
            load(strcat(OUTDIR,outfileName),'-mat');
            sampleSize = min(size(featsAll,1),size(a,1));
            %sampleSize = 10;
            
            a = a(1:sampleSize,:)'; 
            featsAll = featsAll(1:sampleSize,:)';
            inputs = [inputs,a];
            targets = [targets,featsAll];
            if(count==numUttsToWork)
                break;
            end
        end
end

clearvars -except inputs targets
%Making inputs 0 mean and unit variance
%[inputs,inpSettings] = mapstd(inputs);
%[targets,tarSettings] = mapstd(targets);
disp('All data loaded');

% Create a Fitting Network
hiddenLayerSize = 10;
net = fitnet(hiddenLayerSize);

% Choose Input and Output Pre/Post-Processing Functions
% For a list of all processing functions type: help nnprocess
net.inputs{1}.processFcns = {'removeconstantrows','mapminmax'};
net.outputs{2}.processFcns = {'removeconstantrows','mapminmax'};


% Setup Division of Data for Training, Validation, Testing
% For a list of all data division functions type: help nndivide
net.divideFcn = 'dividerand';  % Divide data randomly
net.divideMode = 'sample';  % Divide up every sample
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% For help on training function 'trainlm' type: help trainlm
% For a list of all training functions type: help nntrain
net.trainFcn = 'trainlm';  % Levenberg-Marquardt

% Choose a Performance Function
% For a list of all performance functions type: help nnperformance
net.performFcn = 'mse';  % Mean squared error

% Choose Plot Functions
% For a list of all plot functions type: help nnplot
net.plotFcns = {'plotperform','plottrainstate','ploterrhist', ...
  'plotregression', 'plotfit'};

disp('Starting to train the neural network.');
% Train the Network
[net,tr] = train(net,inputs,targets);

% Test the Network
outputs = net(inputs);
errors = gsubtract(targets,outputs);
performance = perform(net,targets,outputs)

% Recalculate Training, Validation and Test Performance
trainTargets = targets .* tr.trainMask{1};
valTargets = targets  .* tr.valMask{1};
testTargets = targets  .* tr.testMask{1};
trainPerformance = perform(net,trainTargets,outputs)
valPerformance = perform(net,valTargets,outputs)
testPerformance = perform(net,testTargets,outputs)

% View the Network
view(net)
save('ttsModelF300.mat');
disp(['Training completed sucessfully on ',num2str(numUttsToWork),' files']);

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotfit(net,inputs,targets)
%figure, plotregression(targets,outputs)
%figure, ploterrhist(errors)
